# Generated by Django 2.2.6 on 2019-11-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_item_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('farmname', models.CharField(max_length=50)),
                ('farmlocation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Cows', 'Cows'), ('Chicken', 'Chicken'), ('Ducks', 'Ducks'), ('Goats', 'Goats')], max_length=10),
        ),
    ]
